Feature('Learner')

Scenario('Navigate through Serlo', ({ I }) => {
  I.amOnPage('/')
  I.see('Hier auf Serlo')
  I.click('Über Serlo')
  I.see('Serlo.org bietet')
  I.see('Partner und Förderer')
  I.click('Mathematik')
  I.see('Im Mathematik-Bereich')
  I.click('Alle Themen')
  I.see('Mathe')
  I.see('Bereiche')
  I.click('Zahlen und Größen')
  I.click('Grundrechenarten')
  I.see('Plus, minus, mal und geteilt')
  I.click('Rechentricks für die Addition')
  I.see('Trick 1: 10er sammeln')
  I.click('Grundrechenarten')
  I.click('Aufgaben zur Addition natürlicher Zahlen')
  I.see('Zähle folgende einstellige Zahlen zusammen')
  I.see('2+5')
  I.dontSee('Grundwissen')
  I.click('Lösung anzeigen')
  I.see('Grundwissen')
  I.click('Lösung ausblenden')
  I.dontSee('Grundwissen')
  I.scrollPageToBottom()
  I.see('Kommentare')
  I.click('1')
  I.see('Zähle folgende einstellige Zahlen zusammen')
  I.click('Die freie Lernplattform')
  I.click('Nachhaltigkeit')
  I.click('Alle Themen')
  I.click('7 Fakten zum Klimawandel')
  I.click('Video abspielen von YouTube')
  I.click('Teilen')
  I.see('Weitergeben!')
  I.click('Schließen')
  I.click('Spenden')
  I.see('Deine Spende für freie Bildung')
  I.usePlaywrightTo('go back', async ({ page }) => {
    await page.goBack()
  })
  I.click('7 Fakten zum Klimawandel')
})
